#!/bin/sh
system="$(nix eval --impure --raw --expr 'builtins.currentSystem')"
flakeAttr="l460.$system.efiPackage"

# REF: https://github.com/ggPeti/param-pkg/issues/1
pathToConfig="./Nix/include/config.nix"
args="$@"
[ -f ${pathToConfig} ] || pathToConfig="$(nix store add ./Nix/include/sample.nix -n sampleConfig.nix)"
args="--override-input configFile path:${pathToConfig} $args"

nix build .#opencoreConfigurations.${flakeAttr} $args
