#!/bin/sh
system="$(nix eval --impure --raw --expr 'builtins.currentSystem')"
flakeAttr="l460.$system.efiPackage"

# REF: https://github.com/ggPeti/param-pkg/issues/1
configFile="./Nix/include/config.nix"
args="$@"
[ -f ${configFile} ] && args="--override-input configFile path:${configFile} $args"

nix build .#opencoreConfigurations.${flakeAttr} $args
